---
title: "ANCOVA"
author: "Jonas Kristoffer Lindeløv"
date: "September 5, 2018"
output: html_document
---


```{r}
make_data = function(N, mu, r) {
  correlated = MASS::mvrnorm(N, mu=c(0,0), Sigma=cbind(c(1, r), c(r, 1)), empirical=TRUE)
  group_means = c(rnorm_fixed(N, 0), rnorm_fixed(N, mu/2), rnorm_fixed(N, mu))
  
  dd = rnorm_fixed(N*3, sd=0.5)
  
  data.frame(
    # Dependent
    #value = group_means + correlated[, 1],
    value = group_means + dd,
    
    # Independents
    #age = correlated[, 2],
    age = dd,
    group = rep(c('a', 'b', 'c'), each=N),
    
    # Dummy coding of group
    group_a = rep(c(1, 0, 0), each=N),
    group_b = rep(c(0, 1, 0), each=N),
    group_c = rep(c(0, 0, 1), each=N)
  )
}

make_data(5, 1, 0.95)
```


```{r simulate, cache=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)

# Parameters
#Ns = c(seq(from=6, to=20, by=2), 30, 50, 80)
Ns = c(6, 10, 15, 20, 50)
mus = c(0, 0.5, 1)  # Means
rs = c(0, 0.5, 0.95)
PERMUTATIONS = 1:20

# Run it
D = expand.grid(set=PERMUTATIONS, mu=mus, N=Ns, r=rs) %>%
  mutate(
    # Make data
    data = pmap(list(N, mu, r), make_data),
    
    # Tests
    aov_raw = map(data, ~aov(.x[,1] ~ .x[,2] + .x[,3])),
    aov = map(aov_raw, broom::tidy),  # row 1 is age, row 2 is group
    lm_full = map(data, ~lm(.x[,1] ~ 1 + .x[,2] + .x[,3])),
    
    # Extracting statistics for age
    aov_age = map(aov, function(x) x[1,]),
    null_age = map(data, ~lm(.x[,1] ~ 1 + .x[,3])),  # As a function of group only
    lrt_age = map2(null_age, lm_full, ~anova(.x, .y)),
    lag = map(lrt_age, ~broom::tidy(.x)[2,]),
    
    # Extracting statistics for group
    aov_group = map(aov, function(x) x[2,]),
    null_group = map(data, ~lm(.x[,1] ~ 1 + .x[,2])),  # As a function of age only
    lrt_group = map2(null_group, lm_full, ~anova(.x, .y)),
    lgr = map(lrt_group, ~broom::tidy(.x)[2,])
  ) %>%
  
  # Take them out of the tibbles
  unnest(aov_group, aov_age, lgr, lag, .sep='_')

D
```

```{r}
ggplot(D, aes(x=aov_group_p.value, y=lgr_p.value - aov_group_p.value, color=factor(N))) + 
  geom_line() + 
  facet_grid(mu ~ r)
```


# Why is it so perfect!!??
```{r}
D1 = D$data[[1]]
tidy(aov(value ~ group + age, D1))
full = lm(value ~ age + group, D1)
null_group = lm(value ~ age, D1)
null_age = lm(value ~ group, D1)
tidy(anova(null_group, full))
anova(null_age, full)
```

